package com.motomami.errorhandling;

import lombok.Getter;

@Getter
public enum ErrorCode {
    CONTAINS_INVALID_CHARACTERS("CONTAINS_INVALID_CHARACTERS"),
    PASSWORD_HISTORY_VIOLATION("PASSWORD_HISTORY_VIOLATION"),
    NAME_ALREADY_USED("NAME_ALREADY_USED"),
    INVALID_TOKEN("INVALID_TOKEN"),
    CONFIGURATION_ERROR("CONFIGURATION_ERROR"),
    UNDEFINED("UNDEFINED"),
    EMAIL_IN_USERNAME_EXISTS("EMAIL_IN_USERNAME_EXISTS"),
    USERNAME_IN_EMAIL_EXISTS("USERNAME_IN_EMAIL_EXISTS"),
    CANNOT_IMPORT_CONFIG_FROM_FILE("CANNOT_IMPORT_CONFIG_FROM_FILE"),
    CANNOT_IMPORT_CONFIG_FROM_URL("CANNOT_IMPORT_CONFIG_FROM_URL"),
    CANNOT_UPDATE_IDP_INTERNAL_NAME_OR_TYPE("CANNOT_UPDATE_IDP_INTERNAL_NAME_OR_TYPE"),
    USER_CANNOT_BE_UPDATED("USER_CANNOT_BE_UPDATED"),
    NOT_FOUND("NOT_FOUND"),
    ACCESS_NOT_GRANTED("ACCESS_NOT_GRANTED"),
    MODULE_CANNOT_BE_UPDATED("MODULE_CANNOT_BE_UPDATED"),
    IDP_CANNOT_BE_CREATED("IDP_CANNOT_BE_CREATED"),
    DEFAULT_IDP_DISABLED("DEFAULT_IDP_DISABLED"),
    GROUP_MAPPING_MISSING_REQUIRED_FIELD("GROUP_MAPPING_MISSING_REQUIRED_FIELD"),
    GROUP_MAPPING_ALREADY_EXISTS("GROUP_MAPPING_ALREADY_EXISTS");

    private final String codeMsg;

    ErrorCode(String codeMsg) {
        this.codeMsg = codeMsg;
    }
}

